services:
  database-source:
    image: mariadb:11.4-noble
    container_name: kamiodagames_db_source
    # ホスト公開しない（ports削除）。内部向けに3306をexpose（任意）
    expose:
      - "3306"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./data/mariadb/source:/var/lib/mysql
      - ./data/healthcheck:/healthcheck
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kamiodagamesid
    command: --server-id=1 --log-bin --binlog-do-db=kamiodagamesid
    healthcheck:
      test: ["CMD", "/healthcheck/mariadb.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend
  database-replica:
    image: mariadb:11.4-noble
    container_name: kamiodagames_db_replica
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kamiodagamesid
    command: --server-id=2 --relay-log=mysql-relay-bin --log-bin --binlog-do-db=kamiodagamesid --read-only=1
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./data/mariadb/replica:/var/lib/mysql
      - ./data/healthcheck:/healthcheck
    depends_on:
      database-source:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/healthcheck/mariadb.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend
  apiserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20400:8080"   # ホスト20400 → コンテナ8080（APIのみ公開）
    depends_on:
      database-source:
        condition: service_healthy
      database-replica:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - ./data:/app/data
networks:
  backend:
    driver: bridge
